<a href="https://colab.research.google.com/github/Nikila-K/Assignments/blob/main/Nikila_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt

In [ ]:
#loading the data

In [2]:
from google.colab import files
files.upload()

Saving car_age_price.csv to car_age_price.csv


{'car_age_price.csv': b'Year,Price\r2018,465000\r2019,755000\r2019,700000\r2018,465000\r2018,465000\r2015,350000\r2016,425000\r2017,575000\r2017,509999\r2017,575000\r2019,500000\r2018,500000\r2017,500000\r2019,600000\r2017,475000\r2017,500000\r2017,500000\r2017,550000\r2019,500000\r2017,500000\r2018,500000\r2019,500000\r2015,434999\r2017,550000\r2017,550000\r2017,550000\r2017,550000\r2017,550000\r2017,550000\r2017,550000\r2019,650000\r2017,550000\r2017,550000\r2017,550000\r2017,450000\r2017,550000\r2017,550000\r2017,486000\r2018,475000\r2020,545000\r2019,525000\r2019,600000\r2018,550000\r2019,550000\r2019,550000\r2018,450000\r2019,500000\r2018,450000\r2016,396000\r2018,600000\r2013,325000\r2018,550000\r2013,345000\r2013,345000\r2017,525000\r2017,550000\r2014,341000\r2017,550000\r2014,450000\r2016,550000\r2015,490000\r2017,540000\r2017,540000\r2017,595000\r2015,490000\r2017,495000\r2017,525000\r2015,400000\r2015,465000\r2015,300000\r2015,450000\r2017,490000\r2015,300000\r2013,320000\r20

In [3]:
data=pd.read_csv('car_age_price.csv')

In [7]:
data.head()

Year   Price
0  2018  465000
1  2019  755000
2  2019  700000
3  2018  465000
4  2018  465000

In [ ]:
#checking the basic details

In [8]:
data['Year'].value_counts()

2017    47
2015    22
2019    12
2018    11
2016     6
2014     6
2020     4
2013     4
Name: Year, dtype: int64

In [9]:
data['Price'].value_counts()

550000    20
520000    11
500000    10
450000     6
490000     5
400000     5
600000     4
465000     4
300000     4
425000     3
350000     3
390000     3
525000     3
325000     3
375000     2
475000     2
575000     2
345000     2
320000     2
700000     2
540000     2
640000     1
480000     1
409999     1
396000     1
495000     1
595000     1
341000     1
755000     1
545000     1
486000     1
650000     1
434999     1
509999     1
420000     1
Name: Price, dtype: int64

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112 entries, 0 to 111
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Year    112 non-null    int64
 1   Price   112 non-null    int64
dtypes: int64(2)
memory usage: 1.9 KB


In [10]:
data.shape

(112, 2)

In [ ]:
#checking the missing values

In [12]:
data.isnull().sum()

Year     0
Price    0
dtype: int64

In [13]:
data.corr()

Year     Price
Year   1.000000  0.776302
Price  0.776302  1.000000

Linear Regression

In [ ]:
#splitting the data into feature and target

In [14]:
y=data['Price'] #Price as target 
x=data['Year']

In [15]:
from sklearn.model_selection import train_test_split

In [ ]:
#splitting training and test data

In [17]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

Linear Regression 

In [18]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
model=lr.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_test

ValueError: ignored

In [ ]:
#Reshaping the data

In [19]:
Year=data.Year
x=Year.values.reshape(-1,1)

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [21]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
model=lr.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_test

40     525000
65     495000
4      465000
47     450000
42     550000
69     300000
26     550000
11     500000
10     500000
44     550000
73     320000
55     550000
68     465000
97     640000
0      465000
18     500000
53     345000
80     390000
103    375000
91     520000
36     550000
12     500000
31     550000
Name: Price, dtype: int64

In [22]:
y_pred

array([600775.91252081, 505558.77690466, 553167.34471273, 553167.34471273,
       553167.34471273, 410341.6412885 , 505558.77690466, 553167.34471273,
       600775.91252081, 600775.91252081, 315124.50567235, 505558.77690466,
       410341.6412885 , 648384.48032889, 553167.34471273, 600775.91252081,
       315124.50567235, 410341.6412885 , 505558.77690466, 505558.77690466,
       505558.77690466, 505558.77690466, 505558.77690466])

In [ ]:
#Mean squared error

In [23]:
from sklearn.metrics import mean_squared_error,r2_score
print('MSE is: ',mean_squared_error(y_test,y_pred))

MSE is:  4326906256.829671


In [ ]:
#R squared error

In [24]:
print('R Squared value is: ',r2_score(y_test,y_pred))

R Squared value is:  0.36759313425902185


Calculate the possible price of a 2022 model second-hand grand i10

In [25]:
lr.predict([[2022]])

array([743601.61594504])

Lasso Regression

In [32]:
from sklearn.linear_model import Lasso
ls=Lasso(alpha=1)
model=ls.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_test

40     525000
65     495000
4      465000
47     450000
42     550000
69     300000
26     550000
11     500000
10     500000
44     550000
73     320000
55     550000
68     465000
97     640000
0      465000
18     500000
53     345000
80     390000
103    375000
91     520000
36     550000
12     500000
31     550000
Name: Price, dtype: int64

In [33]:
y_pred

array([600774.90747294, 505558.59627394, 553166.75187345, 553166.75187345,
       553166.75187345, 410342.28507493, 505558.59627394, 553166.75187345,
       600774.90747294, 600774.90747294, 315125.97387594, 505558.59627394,
       410342.28507493, 648383.06307244, 553166.75187345, 600774.90747294,
       315125.97387594, 410342.28507493, 505558.59627394, 505558.59627394,
       505558.59627394, 505558.59627394, 505558.59627394])

In [34]:
from sklearn.metrics import mean_squared_error,r2_score
print('MSE is: ',mean_squared_error(y_test,y_pred))

MSE is:  4326859771.015669


In [35]:
print('R Squared value is: ',r2_score(y_test,y_pred))

R Squared value is:  0.3675999284778446
